# Generated by Django 5.1.1 on 2024-09-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NumberRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(db_index=True)),
                ("occurrences", models.PositiveIntegerField(default=1)),
                ("last_datetime", models.DateTimeField(auto_now=True)),
                ("value", models.PositiveIntegerField()),
            ],
        ),
    ]
